"""Platform Monetization and Unit Economics Engine for Real Estate Capital OS.

Implements Sections 21 (*Modelo de monetización*) and 22 (*Economía del negocio*):
- Fee structure modeling (Origination, Structuring, Success, and Performance Fee / Carry)
- European-style Hurdle Rate Waterfall for LP / Investor alignment
- Net Investor return metrics (Net IRR, Net MOIC, Net NPV)
- Platform Unit Economics: GMV, Revenue, Effective Take Rate, and Contribution Margin
"""

from __future__ import annotations

import math
from typing import Dict, List, Optional
import numpy_financial as npf
from pydantic import BaseModel, Field

from core.schemas import Opportunity, UnderwritingModel
from core.underwriting import calculate_metrics


class FeeScheduleConfig(BaseModel):
    """Configuration for platform fees and carry waterfalls (Section 21)."""
    origination_fee_pct: float = Field(default=0.015, ge=0.0, le=0.10, description="1.5% fee on projected purchase price")
    structuring_fee_pct: float = Field(default=0.010, ge=0.0, le=0.10, description="1.0% fee on total capital required")
    success_fee_pct: float = Field(default=0.015, ge=0.0, le=0.10, description="1.5% fee on gross exit proceeds")
    carry_percentage: float = Field(default=0.20, ge=0.0, le=0.50, description="20% carry on upside profit above hurdle")
    hurdle_rate_annual: float = Field(default=0.12, ge=0.0, le=1.0, description="12% preferred annual return hurdle rate")
    direct_cost_pct_of_revenue: float = Field(default=0.15, ge=0.0, le=0.50, description="15% direct transactional costs")


class FeeBreakdown(BaseModel):
    """Detailed breakdown of platform fees generated by an opportunity."""
    origination_fee: float
    structuring_fee: float
    success_fee: float
    performance_fee: float
    total_platform_revenue: float


class NetInvestorMetrics(BaseModel):
    """True financial yield realized by the investor after all platform fees and carry."""
    net_capital_deployed: float
    net_profit: float
    net_irr_annualized: float
    net_moic: float
    net_npv: float
    net_cashflows: List[float]


class PlatformUnitEconomics(BaseModel):
    """Unit economics of the transaction for Real Estate Capital OS (Section 22)."""
    gmv: float
    platform_revenue: float
    effective_take_rate: float
    direct_costs: float
    contribution_margin: float
    contribution_margin_pct: float


class DealMonetization(BaseModel):
    """Comprehensive monetization and economics model for a deal."""
    opportunity_id: str
    fee_breakdown: FeeBreakdown
    net_investor_metrics: NetInvestorMetrics
    unit_economics: PlatformUnitEconomics
    hurdle_rate_annual: float
    carry_earned: float


def calculate_deal_monetization(
    opportunity: Opportunity,
    underwriting: UnderwritingModel,
    config: Optional[FeeScheduleConfig] = None,
) -> DealMonetization:
    """Compute platform fee schedule, hurdle waterfall, net investor returns, and unit economics."""
    cfg = config or FeeScheduleConfig()

    # 1. Upfront Platform Fees (Entry)
    origination_fee = round(opportunity.projected_purchase_price * cfg.origination_fee_pct, 2)
    structuring_fee = round(opportunity.total_capital_required * cfg.structuring_fee_pct, 2)
    upfront_fees = round(origination_fee + structuring_fee, 2)

    # 2. Exit Success Fee
    success_fee = round(opportunity.projected_exit_value * cfg.success_fee_pct, 2)

    # 3. Base Cashflow Schedule for Investor
    duration = max(1, opportunity.holding_period_months)
    investor_initial_outflow = -(round(opportunity.total_capital_required + upfront_fees, 2))

    # Construct cashflow series prior to carry
    pre_carry_cfs: List[float] = [0.0] * (duration + 1)
    pre_carry_cfs[0] = investor_initial_outflow

    # Copy operating cashflows from asset underwriting
    for m in range(1, duration):
        pre_carry_cfs[m] = underwriting.monthly_cashflows[m] if m < len(underwriting.monthly_cashflows) else 0.0

    # Final month exit proceeds net of asset exit fees and platform success fee
    final_gross_exit = underwriting.monthly_cashflows[duration] if duration < len(underwriting.monthly_cashflows) else 0.0
    pre_carry_cfs[duration] = round(final_gross_exit - success_fee, 2)

    # 4. Preliminary Metrics to check Hurdle Rate
    pre_metrics = calculate_metrics(pre_carry_cfs, discount_rate_annual=underwriting.discount_rate_annual)
    pre_irr = pre_metrics["irr_annualized"]

    # 5. Performance Fee / Carry Waterfall
    performance_fee = 0.0
    if pre_irr > cfg.hurdle_rate_annual:
        # Calculate capital needed at hurdle rate to return principal + preferred return
        monthly_hurdle = (1.0 + cfg.hurdle_rate_annual) ** (1.0 / 12.0) - 1.0
        
        # Present value of all operating flows prior to exit
        # Capital required at exit for hurdle: compounded initial outlay - compounded interim operating cashflows
        hurdle_fv_required = abs(investor_initial_outflow) * ((1.0 + monthly_hurdle) ** duration)
        for m in range(1, duration):
            if pre_carry_cfs[m] != 0.0:
                hurdle_fv_required -= pre_carry_cfs[m] * ((1.0 + monthly_hurdle) ** (duration - m))

        excess_proceeds_above_hurdle = max(0.0, pre_carry_cfs[duration] - hurdle_fv_required)
        performance_fee = round(excess_proceeds_above_hurdle * cfg.carry_percentage, 2)

    # 6. Final Net Cashflows for Investor
    net_cashflows: List[float] = list(pre_carry_cfs)
    net_cashflows[duration] = round(pre_carry_cfs[duration] - performance_fee, 2)

    net_metrics = calculate_metrics(net_cashflows, discount_rate_annual=underwriting.discount_rate_annual)

    # 7. Fee Breakdown Summary
    total_revenue = round(origination_fee + structuring_fee + success_fee + performance_fee, 2)
    fee_breakdown = FeeBreakdown(
        origination_fee=origination_fee,
        structuring_fee=structuring_fee,
        success_fee=success_fee,
        performance_fee=performance_fee,
        total_platform_revenue=total_revenue,
    )

    # 8. Platform Unit Economics (Section 22)
    gmv = round(opportunity.projected_purchase_price + opportunity.estimated_capex + opportunity.projected_exit_value, 2)
    take_rate = round(total_revenue / gmv, 4) if gmv > 0 else 0.0
    direct_costs = round(total_revenue * cfg.direct_cost_pct_of_revenue, 2)
    contribution_margin = round(total_revenue - direct_costs, 2)
    cm_pct = round(contribution_margin / total_revenue, 4) if total_revenue > 0 else 0.0

    unit_economics = PlatformUnitEconomics(
        gmv=gmv,
        platform_revenue=total_revenue,
        effective_take_rate=take_rate,
        direct_costs=direct_costs,
        contribution_margin=contribution_margin,
        contribution_margin_pct=cm_pct,
    )

    return DealMonetization(
        opportunity_id=opportunity.id,
        fee_breakdown=fee_breakdown,
        net_investor_metrics=NetInvestorMetrics(
            net_capital_deployed=net_metrics["total_capital_deployed"],
            net_profit=net_metrics["net_profit"],
            net_irr_annualized=net_metrics["irr_annualized"],
            net_moic=net_metrics["moic"],
            net_npv=net_metrics["npv"],
            net_cashflows=net_cashflows,
        ),
        unit_economics=unit_economics,
        hurdle_rate_annual=cfg.hurdle_rate_annual,
        carry_earned=performance_fee,
    )
